# Generated by Django 5.1 on 2024-09-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('job_details', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(max_length=100, null=True)),
                ('job_salary', models.CharField(max_length=100, null=True)),
                ('job_location', models.CharField(max_length=100, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='Media/Company_logo')),
            ],
        ),
    ]
