# Generated by Django 5.1 on 2024-09-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_details',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
