# Generated by Django 5.1 on 2024-09-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_jobmodel_job_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=100, null=True),
        ),
    ]
