# Generated by Django 5.1 on 2024-09-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_jobmodel_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='company_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
