# Generated by Django 5.1 on 2024-09-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_jobmodel_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
