# Generated by Django 5.1 on 2024-09-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_jobmodel_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
