# Generated by Django 5.1 on 2024-09-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_jobmodel_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='application_deadline',
            field=models.DateField(null=True),
        ),
    ]
