# Generated by Django 5.1 on 2024-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_jobmodel_application_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='education',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='requirement',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
