# Generated by Django 5.1 on 2024-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_jobmodel_education_jobmodel_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='requirement',
            field=models.TextField(null=True),
        ),
    ]
